[package]
name = "basic_shell"
version = "0.1.0"
edition = "2021"

[dependencies]
home = "0.5.11"
nix = { version="0.29.0" ,features = ["process","signal", "term"]}
once_cell = "1.20.3"
regex = "1.11.1"
rustix = "0.38.44"
signal-hook = { version = "0.3.17", features=["extended-siginfo"] }
