[package]
name = "basic_shell"
version = "0.1.0"
edition = "2021"

[dependencies]
home = "0.5.11"
nix = { version="0.29.0" ,features = ["process","signal", "term"]}
regex = "1.11.1"
rustix = "0.38.44"
signal-hook = "0.3.17"
